ERROR_REQUEST_BODY_MISSING_DATA = "ERROR_REQUEST_BODY_MISSING_DATA"
ERROR_USER_NAME_ALREADY_EXIST = "ERROR_USER_NAME_ALREADY_EXIST"
USER_ALREADY_LOGGED_IN = "USER_ALREADY_LOGGED_IN"
USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN"

SUCCESS = "SUCCESS"
FAILED = "FAILED"